version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: histlingo-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: histlingo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: histlingo-api
    restart: always
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/histlingo?schema=public"
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres_data:
